"""empty message

Revision ID: 1421f244bc58
Revises: a245dd1d933c
Create Date: 2021-02-04 15:41:02.275135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1421f244bc58'
down_revision = 'a245dd1d933c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag', 'ag_fund_cap_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag', sa.Column('ag_fund_cap_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
