"""empty message

Revision ID: 54063238b9ea
Revises: 6c37ab3f7634
Create Date: 2021-02-04 11:00:18.354137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54063238b9ea'
down_revision = '6c37ab3f7634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag', sa.Column('ag_fund_cap', sa.String(length=20), nullable=True))
    op.add_column('ag', sa.Column('ag_fund_cap_date', sa.String(length=10), nullable=True))
    op.add_column('ag', sa.Column('time', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag', 'time')
    op.drop_column('ag', 'ag_fund_cap_date')
    op.drop_column('ag', 'ag_fund_cap')
    # ### end Alembic commands ###
