"""empty message

Revision ID: 6c37ab3f7634
Revises: 
Create Date: 2020-09-20 14:38:06.750795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c37ab3f7634'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('ag_future_price', sa.Integer(), nullable=False),
    sa.Column('ag_future_averge_price', sa.Integer(), nullable=False),
    sa.Column('ag_future_previous_settlement_price', sa.Integer(), nullable=False),
    sa.Column('ag_fund_price', sa.Float(), nullable=True),
    sa.Column('ag_fund_previous_net_value', sa.Float(), nullable=True),
    sa.Column('ag_fund_net_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ag')
    # ### end Alembic commands ###
