"""empty message

Revision ID: a245dd1d933c
Revises: 
Create Date: 2021-02-04 12:29:43.119728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a245dd1d933c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag', sa.Column('ag_fund_cap', sa.String(length=20), nullable=True))
    op.add_column('ag', sa.Column('ag_fund_cap_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag', 'ag_fund_cap_date')
    op.drop_column('ag', 'ag_fund_cap')
    # ### end Alembic commands ###
